version: '3.8'  # Use the version of Docker Compose you have installed

services:
  mongodb:
    image: mongo:latest  # You can specify a specific MongoDB version here
    container_name: my-mongodb
    ports:
      - "27017:27017"  # Map host port 27017 to container port 27017
    volumes:
      - ./data:/data/db  # Mount a local directory for data persistence
    environment:
      MONGO_INITDB_ROOT_USERNAME: stream
      MONGO_INITDB_ROOT_PASSWORD: stream1234
    networks:
      - my-network  # Attach the container to a custom network
    command: --auth
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
networks:
  my-network:
    driver: bridge  # You can use a different network driver if needed
