# Use an official Node.js runtime as the base image
FROM node:12.13.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Expose the port your Nest.js application will listen on (e.g., 3000)
EXPOSE 3000

# Start your Nest.js application when the container starts
CMD ["npm", "start"]
